#!/usr/bin/env python3

import inspect, os, argparse


# ===============================================================
# Finding real script path…

script_name = os.path.abspath(inspect.stack()[0][1])
script_path = os.path.dirname(os.path.abspath(inspect.stack()[0][1]))
working_dir = os.getcwd()


# ===============================================================
# https://docs.python.org/3.5/library/argparse.html#the-add-argument-method


parser = argparse.ArgumentParser(description='Time Backup')
parser.add_argument('--verbose', '-v', action='count')
parser.add_argument('--debug', '-d', action='store_true')
parser.add_argument('SRC', nargs='+')
parser.add_argument('DST', nargs=1)


args = parser.parse_args()
print(args)


print(working_dir)