#!/usr/bin/env python3

import inspect, os, argparse

def arguments_parse_destination(path):

	return path

def arguments_parse_source(path):

	return path

def arguments_get():
	"""
	parse arguments
	ref: https://docs.python.org/3.5/library/argparse.html#the-add-argument-method

	"""

	parser = argparse.ArgumentParser(description='Time Backup')
	parser.add_argument('-v', '--verbose', action='count', help='add verbosity, can be added multiple times')
	parser.add_argument('-d', '--debug', action='store_true', help='add debug output')
	parser.add_argument('source', nargs='+', help='these are directly passed to rsync')
	parser.add_argument('destination', nargs=1, help='used as base path for backups')
	args = parser.parse_args()

	args.source = arguments_parse_source(args.source)
	args.destination = arguments_parse_destination(args.destination)

	return args



if __name__ == "__main__":

	script_name = os.path.abspath(inspect.stack()[0][1])
	script_path = os.path.dirname(os.path.abspath(inspect.stack()[0][1]))
	working_dir = os.getcwd()

	arguments = arguments_get()

	print(arguments)
	print(working_dir)
	#parse_file(arguments)